exe_resaver = "C:\\Program Files (x86)\\1C Game Studios\IL-2 Sturmovik Great Battles\\bin\\resaver\\MissionResaver.exe"
path_data = "C:\\Program Files (x86)\\1C Game Studios\IL-2 Sturmovik Great Battles\\data"
path_mlg = "C:\\Program Files (x86)\\1C Game Studios\IL-2 Sturmovik Great Battles\\data"
path_raw_missions = "C:\\Program Files (x86)\\1C Game Studios\IL-2 Sturmovik Great Battles\\data\\Multiplayer\\raw_missions"
path_dogfight = "C:\\Program Files (x86)\\1C Game Studios\IL-2 Sturmovik Great Battles\\data\\Multiplayer\\Dogfight"
path_mission = "C:\\Program Files (x86)\\1C Game Studios\IL-2 Sturmovik Great Battles\\data\\Multiplayer\\raw_missions\\AAS_Novorossiysk_summer.Mission"
